import axios from "axios";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import MarketingComp from "@/components/MarketingComp";
import KomisiComp from "@/components/KomisiComp";
import TransaksiComp from "@/components/TransaksiComp";
import TunaiComp from "@/components/TunaiComp";
import KreditComp from "@/components/KreditComp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar bg-body-tertiary shadow-sm">
        <div className="container-fluid ">
          <a
            className="navbar-brand fw-bold d-flex justify-content-centerr"
            href="#"
          >
            <div className="text-center">Herca</div>
          </a>
        </div>
      </nav>

      <div className="px-5 pt-5">
        <div className="d-flex justify-content-start">
          <div className="col-5 pe-1">
            <TunaiComp />
          </div>
          <div className="col-5 ps-2">
            <KreditComp />
          </div>
          <div className="col-lg-2 col-12 ps-lg-2">
            <MarketingComp />
          </div>
        </div>
        <div className="d-flex justify-content-start flex-wrap">
          <div className="col-lg-6 col-12 pe-lg-2">
            <KomisiComp />
          </div>
          <div className="col-lg-6 col-12 ">
            <TransaksiComp />
          </div>
        </div>
      </div>
    </>
  );
}
