import axios from "axios";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import Head from "next/head";

export default function Marketing() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axios.get(`/api/marketing`);
        setPosts(response.data.data);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container pt-5">
        <div className="card mt-5 p-3">
          <table className="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nama</th>
              </tr>
            </thead>
            <tbody>
              {posts.map((item: any) => (
                <tr>
                  <td>{item.id}</td>
                  <td>{item.name}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
